param(
  [string]$From = $env:QQ_SMTP_USER,
  [string]$AuthCode = $env:QQ_SMTP_AUTH_CODE,
  [string]$To = '1943358991@qq.com',
  [string]$ProjectName = 'RenMai',
  [string]$Stage = 'Status Update',
  [string]$SummaryFile,
  [string]$ConfigFile,
  [string]$BodyTemplateFile,
  [string[]]$Attachments,
  [switch]$DryRun
)

Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'

$subject = "[$ProjectName] $Stage"
$timestamp = Get-Date -Format 'yyyy-MM-dd HH:mm:ss'

$templatePath = $BodyTemplateFile
if (-not $templatePath) {
  $defaultTemplatePath = Join-Path $PSScriptRoot 'templates\project-update-body.txt'
  if (Test-Path -LiteralPath $defaultTemplatePath) {
    $templatePath = $defaultTemplatePath
  }
}

$summaryText = @(
  '- Current app and web updates are ready for review.'
  '- Copyright application materials can be prepared next.'
) -join "`r`n"

if ($SummaryFile) {
  if (-not (Test-Path -LiteralPath $SummaryFile)) {
    throw "Summary file not found: $SummaryFile"
  }

  $summaryText = Get-Content -LiteralPath $SummaryFile -Raw -Encoding UTF8
}

if ($templatePath) {
  $templateText = Get-Content -LiteralPath $templatePath -Raw -Encoding UTF8
  $body = $templateText.Replace('{{PROJECT_NAME}}', $ProjectName)
  $body = $body.Replace('{{STAGE}}', $Stage)
  $body = $body.Replace('{{TIMESTAMP}}', $timestamp)
  $body = $body.Replace('{{SUMMARY}}', $summaryText.Trim())
}
else {
  $bodyLines = @(
    'Hello,'
    ''
    'This is an automated project status email.'
    "Project: $ProjectName"
    "Stage: $Stage"
    "Time: $timestamp"
    ''
    'Summary:'
    $summaryText
    ''
    'This email was generated by scripts/send-project-update.ps1.'
  )

  $body = $bodyLines -join "`r`n"
}

$mailScript = Join-Path $PSScriptRoot 'send-qq-mail.ps1'

$mailParams = @{
  Subject = $subject
  Body = $body
  DryRun = $DryRun
}

if ($From) {
  $mailParams.From = $From
}
if ($AuthCode) {
  $mailParams.AuthCode = $AuthCode
}
if ($To) {
  $mailParams.To = $To
}
if ($ConfigFile) {
  $mailParams.ConfigFile = $ConfigFile
}
if ($Attachments) {
  $mailParams.Attachments = $Attachments
}

& $mailScript @mailParams
